name: Mark stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ github.token }}
        stale-issue-message: "Esta issue foi marcada porque est치 aberta e est치 h치 mais de 60 dias sem nenhuma atividade. Em breve ser치 fechada."
        close-issue-message: "Esta issue foi fechada porque estava marcada e continuou sem atividade por 60 dias, desde que foi marcada."
        days-before-issue-stale: 60
        days-before-issue-close: 5
