name: Mark stale issues and pull requests

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:

  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
    
    - uses: actions/stale@v8
      with:
        repo-token: ${{ github.token }}
        stale-issue-message: "Esta vaga foi marcada como `stale` porque está aberta à mais de 60 dias sem nenhuma atividade. Em 5 dias será encerrada."
        close-issue-message: "Esta vaga foi encerrada porque estava marcada como `stale` e continuou sem atividade por 5 dias."
        days-before-issue-stale: 60
        days-before-issue-close: 5
